version: '3'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend-products-solds
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./api-products-solds
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:admin123@database:5432/db 
    depends_on:
      - database
    restart: "on-failure"

volumes:
  pg_data:
